"""initial migrations

Revision ID: b33914532ad7
Revises: 
Create Date: 2026-05-20 09:43:25.089019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b33914532ad7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_usuarios_nome'), 'usuarios', ['nome'], unique=False)
    op.create_table('feiras',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('orcamento', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('valor_previsto', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feira_itens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('preco_varejo', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('preco_atacado', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('qtd_minima_atacado', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_escolhido', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('unidade_medida', sa.String(), nullable=False),
    sa.Column('imagem_url', sa.String(), nullable=True),
    sa.Column('ocr_texto', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('feira_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['feira_id'], ['feiras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notas_fiscais',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mercado_nome', sa.String(), nullable=False),
    sa.Column('valor_total', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('data_compra', sa.DateTime(), nullable=False),
    sa.Column('qr_code', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('feira_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['feira_id'], ['feiras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nota_fiscal_itens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('produto_nome', sa.String(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('preco_total', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('divergencia', sa.Boolean(), nullable=False),
    sa.Column('valor_esperado', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('diferenca', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('nota_fiscal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['nota_fiscal_id'], ['notas_fiscais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nota_fiscal_itens')
    op.drop_table('notas_fiscais')
    op.drop_table('feira_itens')
    op.drop_table('feiras')
    op.drop_index(op.f('ix_usuarios_nome'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###